### ISSUE TITLE
Authentification by wattpilot-HA possible?

### ISSUE THREAD

**Issue by oilid** [mk-maddin/wattpilot-HA#54]
Hello,

is it possible to use this authentifaction button by wattpilot-HA?

![grafik](https://github.com/user-attachments/assets/887b8ad3-b752-4a26-92bd-0b5c98d5c04b)

I can't find any switch or button for this...

Thanks for an answer,
Oilid

**Comment by HABrain** [comment]
Hi Oilid,
I work on the same topic.
If you install this integration you find a lot of Entitys. One of them is called "Wattpilot start charging".
The problem is: if you set up your wattpilot to have to authenticate before start charging, the watt pilot waits for authentificat by the ID-chip or to start charging by the app.
I did't find the way to authenticate by homeassistant.

In an other forum I find a hint to give the authentication in the code. 
https://www.photovoltaikforum.com/thread/235419-aktive-steuerung-der-akkunutzung/ (Topic #10 from 18th Sept. 2024)
Unfortunately, I'm not familiar enough with it to know how to use it. 

Maybe you find the way...

**Comment by mk-maddin** [comment]
Hi Both,

@HABrain I cannot confirm the link you shared is about wattpilot authentication - the topic discussed there is about authentication to the fronius inverter and changing the inverter (not wattpilot) values to not discharge your home battery for charging the car. 
Furthermore please note that what is described in post 10 is fronius undocumented and unsupported which means this can change with every release.

@oilid As of my latest understanding and wattpilot documentations I found this is by design - As I am not using the authentication mechanism, can you start charging by the official wattpilot APP, without the ID Chip if you have enabled authentication?

**Comment by oilid** [comment]
@mk-maddin As shown in the screenshot by the app and the button "Authentifizieren". Its an alternative to the ID Chip if authentification is enabled...

**Comment by mk-maddin** [comment]
Thanks - so after you press "authentifizieren" you do not need to insert anything additional? 
(Mainly for my own interest) To which Chip is the charging then booked within the statistics?

Can you please share the HA diagnostics information so I can see if you have additional enable/disable option for the "authentifzieren" button?

**Comment by oilid** [comment]
> Thanks - so after you press "authentifizieren" you do not need to insert anything additional?
After pressing "authentifizieren" it starts the charging with the eco, next trip or normal mode automatically if the corresponding parameters (for example for eco) are true.

> (Mainly for my own interest) To which Chip is the charging then booked within the statistics?
Unfortunately i have only one chip (without using it) and car configured. It works for me when I only use the app (instead of the RFID Chip). The statistics are for me correct.

> Can you please share the HA diagnostics information so I can see if you have additional enable/disable option for the "authentifzieren" button?
How can I share the HA diagnostics information? I'm new to HA...

**Comment by oilid** [comment]
Thanks. Here we go: 
[config_entry-wattpilot-01J9RHJYCPX6JG4B5QJT70D1RD.json](https://github.com/user-attachments/files/18382896/config_entry-wattpilot-01J9RHJYCPX6JG4B5QJT70D1RD.json)

at 23:06 I pressed “authenfizieren” in the app and then at 23:08 I started charging with default mode by your HA-integration and is still on going..
Do you need more informations?

**Comment by HABrain** [comment]
Hey oilid,
did I understand your last post correct?
You have started the charging with the HA-integration?
Or did you started with the App or the RFID-chip?

Many greetings

**Comment by oilid** [comment]
First I pressed the “authentifizieren”-button in the app and then it starts charging if the mode allows it… but i changed the mode to default by your HA-integration. With the default mode it will start charging immediately…

**Comment by HABrain** [comment]
yes, then it starts without authentication.

But that's not an option for me. My wallbox is at my parking space. Someone else could charge there too.

**Comment by mk-maddin** [comment]
Thanks for the diagnostics.
What I have found is that the value "cll" seems to be responsible to control the access allow/not allow behaviour.
In case the cable is locked we see a "cll" value of:

`namespace(accessControl=0,  cableCurrentLimit=32, currentLimitMax=32, requestedCurrent=10, temperatureCurrentLimit=32, unsymetryCurrentLimit=32)`
for 22kW Wattpilot version
`namespace(accessControl=0, adapterCurrentLimit=16, cableCurrentLimit=32, currentLimitMax=16, requestedCurrent=16, temperatureCurrentLimit=32, unsymetryCurrentLimit=32) `
for 11KW Wattpilot version

If the access is authorized/authentifiziert, I can see that the property of 'accessControl' is removed completely.
So values are then:

`namespace(cableCurrentLimit=32, currentLimitMax=32, requestedCurrent=10, temperatureCurrentLimit=32, unsymetryCurrentLimit=32)`
for 22kW Wattpilot version
`namespace(adapterCurrentLimit=16, cableCurrentLimit=32, currentLimitMax=16, requestedCurrent=16, temperatureCurrentLimit=32, unsymetryCurrentLimit=32) `
for 11KW Wattpilot version

At the moment there is no option implemented within the integration (not sure about the upstream py library) to set namespace values (only to read them).

So please do not expect an implementation within short term. I have to check when there is time for it.

**Comment by mk-maddin** [comment]
Ok so investigated further the last days whenever possible.
But as of my current outcome I am not able to set these values at all :/

I will now raise a request / issue to wattpilot python upstream author..maybe he has some more ideas.

The following py script was used for tests:
```
import wattpilot
import time
import json
import types


charger=wattpilot.Wattpilot('<MyWattpilotIP>','<MyWattpilotPassword>')
charger.connect()

timer=0
timeout=30
while timeout > timer and not (charger.connected and charger.allPropsInitialized):
  time.sleep(1)
  timer+=1
if not charger.connected:
  print("Charger not connected")
  exit()
elif not charger.allPropsInitialized:
  print("Charger not initialized")
  charger._wsapp.close()
  exit()
elif not timeout > timer:
  print("Connection timeout")
  exit()
print("Charger connected")


def send_value(charger, identifier, value, force_type=None):
  #print("value = ", value)
  #print("value type =", type(value))
  #print("value dict =", value.__dict__)

  if str(value).lower() in ["false","true"] or force_type == 'bool':
    v=json.loads(str(value).lower())
  elif type(value) is types.SimpleNamespace:
    v=value.__dict__
  elif force_type == 'str':
    v=str(value)
  elif str(value).isnumeric() or force_type == 'int':
    v=int(value)
  elif str(value).isdecimal() or force_type == 'float':
    v=float(value)
  else:
    v=str(value)

  #print("v = ",v)
  #print("v type = ", type(v))
  #print("v dict = ", v.__dict__)

  charger.send_update(identifier,v)

def print_value(charger, identifier):
  print(identifier, " = ", charger.allProps[identifier])


print("====== GET VALUES PRE =======")
print_value(charger, 'ebe') #ebe is boost active/inactive - for simple check in apply if changes applied in general
print_value(charger, 'acs')
print_value(charger, 'ocppcs')
print_value(charger, 'npd')
print_value(charger, 'ebv')
print_value(charger, 'modelStatus')
print_value(charger,'cll')


print("======= SET VALUES =======")
if charger.allProps['ebe'] == True: send_value(charger,'ebe', False)
else: send_value(charger, 'ebe', True)
send_value(charger, 'acs', 1)
send_value(charger,'ocppcs', 1)
send_value(charger, 'npd', True)
send_value(charger, 'ebv', True)
#send_value(charger, 'modelStatus', 17) #ReadOnly value

cll=charger.allProps['cll']
#cll locked 11kW: namespace(accessControl=0, adapterCurrentLimit=16, cableCurrentLimit=32, currentLimitMax=16, requestedCurrent=16, temperatureCurrentLimit=32, unsymetryCurrentLimit=32) 
#cll unlocked 11kW: namespace( adapterCurrentLimit=16, cableCurrentLimit=32, currentLimitMax=16, requestedCurrent=16, temperatureCurrentLimit=32, unsymetryCurrentLimit=32) 
if hasattr(cll, 'accessControl'): del cll.accessControl
send_value(charger, 'cll', cll)

time.sleep(3)

print("====== GET VALUES POST =======")
print_value(charger, 'ebe')
print_value(charger, 'acs')
print_value(charger, 'ocppcs')
print_value(charger, 'npd')
print_value(charger, 'ebv')
print_value(charger, 'modelStatus')
print_value(charger,'cll')

time.sleep(1)

charger._wsapp.close()
```


Outcome as follows:

![Image](https://github.com/user-attachments/assets/58bb65d8-6b61-4159-b102-7e381f52cf24)

**Comment by mk-maddin** [comment]
ok... blame is on my 
I was fully at the wrong path making it way more complex than necessary 🙈

This https://github.com/mk-maddin/wattpilot-HA/commit/8f8f244ae9df07d2c5cea93028a597a1eb327909  adds button to authenticate.
Can you please confirm if this is working from your end, too? 
I can then add it to the next release.

The button is disable by default - so you have to enable it within the device view first

![Image](https://github.com/user-attachments/assets/c0d81137-1de5-45f5-9ae1-d2ecccedb0ab)

Additionally as said this is simply a button - the button entity cannot represent the current state of wattpilot authentication.
The entity 'ID Chip Current' which shows the active id card (in case for the button it is a value of 0 / "No Chip" if authenticated and 999 / "No Transaction" if not authenticated is available - but deactivated by default, too.
So you will have to enable it the same way as the button.

![Image](https://github.com/user-attachments/assets/dc4d48a1-937a-4db5-9502-564e30d1e321)

**Comment by HABrain** [comment]
Thank you for checking this and making the change available. I will check it over the weekend and give you an feedback.

**Comment by HABrain** [comment]
Well, I checked it today.
I added the button in the button.yaml.
In the settings, I unfortunately can't find the "Wattpilot Authenticate" field in the controls area.
After I click on "Wattpilot ID chip Current" in the "Sensors" area, the ID is displayed. But the fields for starting the charging process under "settings" are now deactivated.

**Comment by HABrain** [comment]
<img width="334" alt="Image" src="https://github.com/user-attachments/assets/f0b29510-ba75-4ed7-8fb9-f3ed2fac4608" />

<img width="326" alt="Image" src="https://github.com/user-attachments/assets/eeff45ef-353a-4c09-988c-9a823789be0a" />

**Comment by mk-maddin** [comment]
> ...I unfortunately can't find the "Wattpilot Authenticate" field in the controls area....But the fields for starting the charging process under "settings" are now deactivated.

That sounds to my like there i something wrong with your entry into buttons.yaml as all buttons are no longer loaded ;)
Yaml is very specific to how many spaces or tabs you are allowed to use etc.

I published [beta release 0.2.6](https://github.com/mk-maddin/wattpilot-HA/releases/tag/v0.2.6) which includes the authenticate button commit.
This can be downloaded manually or via HACS using the three dots -> Redownload -> Need a different version

![Image](https://github.com/user-attachments/assets/c346ffb9-56e6-455d-9b3f-761da05af40d)

**Comment by oilid** [comment]
The „Wattpilot Authenticate“-Button works perfect for me in 0.2.6 beta. Thanks a lot :)

**Comment by HABrain** [comment]
After reloading the integration, I now have the same fields as you specified (wattpilot authenticate and the different chip ids.
But I cannot start the charging process.
However, once I have started the charging process with the app, I can stop and restart it with the integration.

**Comment by mk-maddin** [comment]
can you please be more specific on what you do within HA to start the charging process?
It is really hard to help when I am not able to reproduce what you are doing in detailed step-by-step and have no related log message etc.

note that the added button is only to authenticate...it will not start charging automatically.
You will have to additionally "press" the start charging button / set a next trip time / wait for PV surplus, depending on your selected charging mode.

**Comment by HABrain** [comment]
oh man. Now I have a completely different problem...
After trying some settings in the device, I had a setup error in the integration. I couldn't restart it either.
Now I deleted the integration and restarted HA.
Then I reinstalled the integration (version 0.2.3), but I couldn't find the field to install a different version.
But even after the reinstallation I still have the setup error.
The integration was probably not completely deleted. Because the extension for authentication is still in the Button.yaml.
Do you have any idea?

**Comment by mk-maddin** [comment]
To make sure you cleanup I would recommend to:

1. delete the entry from your settings->devices & services page within HA
2. delete the folder /config/custom_components/wattpilot
3. fully restart HA (not only config reload)
4. reinstall wattpilot via HACs ( should allow you for version 0.2.6 pre-release directly) 
5. fully restart HA (not only config reload)
6. add wattpilot integration

**Comment by HABrain** [comment]
Hi,

I restart the HA completely.

But if I load the integration in HACS I receive this message:
Am 22. Jan. 2025, 19:00 +0100 schrieb mk-maddin ***@***.***>:

**Comment by HABrain** [comment]
Hi,

I can´t delete the folder home assistant/custom_components/wattpilot.
I receive the message, the folder is not empty - but it is empty (I delete every file manually). I renamed the folder (before I restart the HA completely).

But if I load the integration in HACS I receive this message:

<img width="436" alt="Image" src="https://github.com/user-attachments/assets/fd67ead5-5ce1-4f65-8ca2-5bf577cd94f4" />

**Comment by HABrain** [comment]
Okay... today the blame is on me...
I found it....

**Comment by mk-maddin** [comment]
Why are you modifying your HACs repositories? 
In none of my steps this is listed...
You just need to reinstall the integration - not re-register the full repository. See: https://hacs.xyz/docs/use/repositories/dashboard/#downloading-a-repository


How are you trying to delete the folder? File explorer addon? Terminal & SSH addon? Directly SSH into the server?

**Comment by HABrain** [comment]
Yes. I try to load it from the repository. But I found in the HACS-list.
And there I found the version 0.2.6 beta.
I tryed to delete the folder with the file editor.
And now I'm back - I find the settings for the wattpilot.

I send you my next questions in a few minutes....

**Comment by HABrain** [comment]
OK. Now I have the status that you can see in your pictures.
But how can I start the charging process now?
I press the button “Wattpilot start charging” – but the charging process doesn’t start.
How can I carry out the authentication beforehand?

**Comment by mk-maddin** [comment]
what do you mean with "all deactivated" are they disabled? then you have to enable the "wattpilot Authenticate" first.

![Image](https://github.com/user-attachments/assets/5126e5e8-06ac-4235-9591-02dc2e115f51)
![Image](https://github.com/user-attachments/assets/cdc2d105-1eb3-442e-8c21-ad1533c49ffd)

**Comment by HABrain** [comment]
Yes, but if I activate this, the four buttons for start/stop or restart are deactivated.

<img width="337" alt="Image" src="https://github.com/user-attachments/assets/fa64a2ff-8f7e-4171-9f56-46deb5d0ebec" />

**Comment by HABrain** [comment]
And when I go back to the main page, I get the same error as before.

<img width="694" alt="Image" src="https://github.com/user-attachments/assets/b5fbf36a-002c-4279-90cf-b7b95837b27e" />

**Comment by mk-maddin** [comment]
which error are you seeing in the logs?

**Comment by HABrain** [comment]
In the logbook ?

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/4eceb779-a110-48f4-b6d5-8804d028df2b" />

**Comment by HABrain** [comment]
In the logbook ?
and some more
<img width="373" alt="Image" src="https://github.com/user-attachments/assets/f6c4b323-3980-4a61-a687-fbb49529da2b" />

**Comment by HABrain** [comment]
When I go back to the settings, I can no longer find the button “Authenticate Wattpilot”
And all the other buttons and settings are all deactivated.

**Comment by mk-maddin** [comment]
no - the general Home Assistant log.

settings-> system-> logs

**Comment by HABrain** [comment]
Hmm. good point.
Theo are some points to the wattpilot-integration:

I tried to enter the password. I get the message that it was saved successfully. But the next time I check, the wrong password is there.

1.
Logger: wattpilot
Quelle: /usr/local/lib/python3.13/site-packages/wattpilot/__init__.py:448
Erstmals aufgetreten: 20:54:21 (1 Vorkommnisse)
Zuletzt protokolliert: 20:54:21

Authentication failed: Wrong password

2.
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.wattpilot.utils
Quelle: custom_components/wattpilot/utils.py:272
Integration: Fronius Wattpilot (Dokumentation)
Erstmals aufgetreten: 20:54:35 (1 Vorkommnisse)
Zuletzt protokolliert: 20:54:35

01JJ7NF3FX6JZBS61EEWJMKDHR - async_ConnectCharger: Timeout - charger not connected: False (15 sec)

3.
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.wattpilot.utils
Quelle: custom_components/wattpilot/utils.py:273
Integration: Fronius Wattpilot (Dokumentation)
Erstmals aufgetreten: 20:54:35 (1 Vorkommnisse)
Zuletzt protokolliert: 20:54:35

01JJ7NF3FX6JZBS61EEWJMKDHR - async_ConnectCharger: Try to restart charger via Wattpilot app

4.
Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:324
Erstmals aufgetreten: 20:54:40 (1 Vorkommnisse)
Zuletzt protokolliert: 20:54:40

Detected that custom integration 'wattpilot' sets option flow config_entry explicitly, which is deprecated at custom_components/wattpilot/config_flow.py, line 131: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please report it to the author of the 'wattpilot' custom integration

**Comment by mk-maddin** [comment]
password saved & password correct are two different things ;)

so re-enter the correct password

**Comment by mk-maddin** [comment]
> The „Wattpilot Authenticate“-Button works perfect for me in 0.2.6 beta. Thanks a lot :)

fixed https://github.com/mk-maddin/wattpilot-HA/releases/tag/v0.2.6
